server:
  port: 2448

spring:
  main:
    allow-circular-references: true
  application: ReadArticlesServer
  datasource:
    url: jdbc:postgresql://rsa-p.postgres.database.azure.com:5432/postgres?&sslmode=require
    username: inkronsane
    password: sahsayter72!
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: keichirosanazaki@gmail.com
    password: nwnfanjtrbgptzps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    cache-names: VerificationCodes
    type: caffeine
    caffeine:
      spec: expireAfterWrite=1m

  flyway:
    depends-on: entityManagerFactory
#    enabled: true
#    locations: classpath:db/migration

logging:
  level:
    com:
      inkronsane:
        ReadArticlesServer: ERROR
